#include "secure_check.h"
#include <stdint.h>
#include <stddef.h>

// generated at build time by tools/gen_target.py
#include "target_blob.h"

// Simple constant-time compare to avoid obvious timing leak (not essential for static challenge)
static int ct_equal(const uint8_t *a, const uint8_t *b, size_t n) {
    uint8_t diff = 0;
    for (size_t i = 0; i < n; i++) diff |= (uint8_t)(a[i] ^ b[i]);
    return diff == 0;
}

int secure_validate(const uint8_t *buf, size_t len) {
    if (!buf || len != 32) return 0;
    return ct_equal(buf, kTarget32, 32);
}

// Flag part2 is stored XOR-obfuscated.
// It's NOT returned unless main asks for it (main only prints on validation success).
static const uint8_t kPart2XorKey = 0xA7;
static const uint8_t kPart2Enc[] = {
    // Encoded bytes for "binary_static_analysis}"
    // Generated by tools/gen_target.py along with kTarget32.
    PART2_ENC_BYTES
};

const char* secure_part2(void) {
    static char out[64];
    size_t n = sizeof(kPart2Enc);
    if (n >= sizeof(out)) n = sizeof(out) - 1;
    for (size_t i = 0; i < n; i++) out[i] = (char)(kPart2Enc[i] ^ kPart2XorKey);
    out[n] = '\0';
    return out;
}
